services:
  # Frontend (Next.js)
  - type: web
    name: ulrika-functional-foods-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://functional-foods-backend.onrender.com

  # Backend (Python/FastAPI)
  - type: web
    name: functional-foods-backend
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python -m uvicorn app.backend.nutrient_analysis:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000 