services:
  # Frontend (Next.js)
  - type: web
    name: functionalfoods
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false

  # Backend (Python/FastAPI)
  - type: web
    name: functionalfoods-api
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
    startCommand: python3 -m uvicorn app.backend.nutrient_analysis:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000 