services:
  # Frontend (Next.js)
  - type: web
    name: ulrika-functional-foods-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 